apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ping-deployment
  namespace: katalog-test
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ping-pod
  template:
    metadata:
      labels:
        ingress: enabled
        app: ping-pod
    spec:
      containers:
      - image: philipbhs/node-ping
        imagePullPolicy: Always
        name: ping-container
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1000Mi"