apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: node-ping-ingress
  namespace: katalog-test
spec:
  rules:
  - host: node-ping-katalog-test.k8s-test.oslo.kommune.no
    http:
      paths:
      - backend:
          serviceName: node-ping-service
          servicePort: 8080
  tls:
  - hosts:
    - node-ping-katalog-test.k8s-test.oslo.kommune.no
